variables:
  azureSubscription: 'Free Trial(1)(08856ff3-d5d7-4a58-b749-94b4b8665feb)'
  functionappName: 'SDLCtask'
  buildConfiguration: 'Release'

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: |
    dotnet restore $(Build.SourcesDirectory)\src\SDLCtask.sln
    dotnet build $(Build.SourcesDirectory)\src\SDLCtask.sln --configuration Release
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--configuration Release --output publish_output'
    projects: '$(Build.SourcesDirectory)\\src\\SDLCtask.sln'
    publishWebProjects: false
    modifyOutputPath: true
    zipAfterPublish: false

- script: ls -R
- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)/src/SDLCtask/publish_output/src"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
    ArtifactName: 'drop'
- task: AzureRmWebAppDeployment@4
  inputs:
    connectionType: 'AzureRM'
    azureSubscription: "$(azureSubscription)"
    appType: 'functionApp'
    webAppName: "$(functionappName)"